In [62]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.io as sio
import seaborn as sns
import random
from collections import Counter
from pprint import pprint
from tabulate import tabulate

In [63]:
data = sio.loadmat('covertype_release/covtype_reduced.mat')

In [64]:
data

{'__header__': b'MATLAB 5.0 MAT-file Platform: nt, Created on: Wed Oct 14 18:35:15 2020',
 '__version__': '1.0',
 '__globals__': [],
 'X_test': array([[2.596e+03, 5.100e+01, 3.000e+00, ..., 0.000e+00, 0.000e+00,
         0.000e+00],
        [2.590e+03, 5.600e+01, 2.000e+00, ..., 0.000e+00, 0.000e+00,
         0.000e+00],
        [2.804e+03, 1.390e+02, 9.000e+00, ..., 0.000e+00, 0.000e+00,
         0.000e+00],
        ...,
        [2.960e+03, 1.190e+02, 1.000e+01, ..., 0.000e+00, 0.000e+00,
         0.000e+00],
        [2.954e+03, 1.380e+02, 1.200e+01, ..., 0.000e+00, 0.000e+00,
         0.000e+00],
        [2.950e+03, 1.650e+02, 1.400e+01, ..., 0.000e+00, 0.000e+00,
         0.000e+00]]),
 'X_train': array([[2410.,   67.,   14., ...,    0.,    0.,    0.],
        [2739.,   90.,   25., ...,    0.,    0.,    0.],
        [3172.,    9.,    7., ...,    0.,    0.,    0.],
        ...,
        [2910.,  117.,   15., ...,    0.,    0.,    0.],
        [3204.,  240.,   17., ...,    0.,    0.,    0.],
        [2802.,   42.,    7., ...,    0.,    0.,    0.]]),
 'y_train': array([[3., 5., 1., 6., 2., 1., 3., 1., 1., 1., 2., 1., 1., 1., 1., 1.,
         1., 1., 2., 2., 1., 3., 2., 1., 2., 2., 1., 3., 2., 2., 1., 2.,
         2., 3., 1., 1., 2., 1., 1., 1., 1., 1., 1., 2., 1., 3., 1., 3.,
         1., 1., 1., 1., 1., 2., 2., 1., 1., 2., 2., 7., 2., 7., 2., 2.,
         1., 1., 1., 2., 2., 1., 2., 2., 1., 1., 2., 1., 2., 1., 2., 1.,
         2., 2., 1., 2., 5., 1., 2., 2., 2., 2., 1., 1., 2., 2., 2., 1.,
         2., 1., 2., 2., 6., 1., 2., 2., 2., 1., 2., 2., 2., 2., 2., 1.,
         1., 3., 2., 6., 6., 2., 7., 2., 5., 6., 1., 1., 1., 2., 1., 2.,
         2., 2., 2., 2., 2., 3., 2., 2., 6., 2., 1., 1., 1., 1., 5., 2.,
         2., 2., 2., 1., 2., 2., 2., 4., 1., 2., 1., 2., 2., 2., 1., 2.,
         2., 6., 3., 1., 3., 1., 1., 2., 2., 7., 2., 1., 3., 2., 6., 3.,
         1., 3., 2., 1., 2., 1., 1., 5., 1., 1., 7., 1., 2., 1., 2., 2.,
         2., 1., 2., 3., 1., 1., 7., 2., 1., 2., 3., 6., 2., 2., 1., 2.,
         6., 2., 6., 1., 7., 1., 1., 2., 2., 2., 2., 2., 1., 2., 2., 2.,
         1., 7., 2., 2., 1., 1., 1., 3., 1., 1., 2., 1., 1., 1., 1., 2.,
         1., 2., 2., 2., 2., 2., 1., 2., 2., 2., 5., 1., 7., 1., 2., 2.,
         1., 7., 2., 2., 2., 1., 2., 1., 3., 1., 1., 1., 1., 2., 2., 2.,
         6., 1., 2., 2., 1., 7., 5., 2., 1., 2., 1., 1., 1., 2., 2., 6.,
         1., 1., 3., 1., 1., 1., 2., 2., 2., 1., 2., 7., 1., 2., 2., 1.,
         1., 1., 2., 3., 1., 2., 2., 2., 2., 1., 1., 2., 1., 3., 2., 2.,
         7., 2., 1., 2., 1., 2., 1., 6., 2., 2., 1., 1., 1., 2., 1., 1.,
         1., 2., 2., 1., 1., 1., 1., 1., 7., 2., 1., 2., 3., 2., 2., 1.,
         2., 2., 2., 1., 6., 1., 1., 1., 2., 6., 1., 1., 2., 3., 1., 2.,
         1., 1., 2., 2., 1., 7., 2., 3., 2., 2., 2., 2., 2., 2., 1., 1.,
         2., 1., 1., 3., 2., 2., 1., 1., 7., 2., 2., 2., 1., 2., 1., 3.,
         1., 2., 2., 1., 1., 2., 3., 2., 3., 1., 2., 1., 1., 1., 1., 2.,
         2., 1., 3., 1., 2., 1., 1., 1., 2., 2., 1., 2., 1., 1., 2., 1.,
         2., 2., 2., 7., 1., 2., 3., 7., 2., 1., 2., 2., 2., 2., 7., 1.,
         3., 1., 2., 2., 1., 2., 1., 2., 1., 3., 2., 2., 1., 3., 1., 3.,
         2., 2., 2., 1.]]),
 'y_test': array([[5., 5., 2., ..., 2., 2., 2.]])}

In [65]:
# XTrain = data['X_train']
# yTrain = data['y_train'][0]

# XTest = data['X_test']
# yTest = data['y_test'][0]

tree = decisionTreeAlgorithm(XTrain, yTrain)
accuracy = calculateAccuracy(XTest,yTest, tree)


tree = decisionTreeAlgorithm(train)
accuracy = calculateAccuracy(test, tree)

In [66]:
XTrain = data['X_train']
yTrain = data['y_train']

XTest = data['X_test']
yTest = data['y_test']

train = np.concatenate((XTrain, yTrain.T),axis=1)
test  = np.concatenate((XTest,  yTest.T), axis=1)

In [67]:
print("Shape of XTrain: "+str(np.shape(XTrain)))
print("Shape of yTrain: "+str(np.shape(yTrain)))
print("Shape of combinedTrain: "+str(np.shape(train)))

print("Shape of XTest: "+str(np.shape(XTest)))
print("Shape of yTest: "+str(np.shape(yTest)))
print("Shape of combinedTest: "+str(np.shape(test)))

Shape of XTrain: (468, 54)
Shape of yTrain: (1, 468)
Shape of combinedTrain: (468, 55)
Shape of XTest: (116202, 54)
Shape of yTest: (1, 116202)
Shape of combinedTest: (116202, 55)

In [68]:
trainDf = pd.DataFrame(train)
columns = ['Elevation', 'Aspect', 'Slope', 'Horizontal_Distance_To_Hydrology', 'Vertical_Distance_To_Hydrology', 'Horizontal_Distance_To_Roadways', 'Hillshade_9am', 'Hillshade_Noon', 'Hillshade_3pm', 'Horizontal_Distance_To_Fire_Points', 'Wilderness_Area1', 'Wilderness_Area2', 'Wilderness_Area3', 'Wilderness_Area4', 'Soil_Type1', 'Soil_Type2', 'Soil_Type3', 'Soil_Type4', 'Soil_Type5', 'Soil_Type6', 'Soil_Type7', 'Soil_Type8', 'Soil_Type9', 'Soil_Type10', 'Soil_Type11', 'Soil_Type12', 'Soil_Type13', 'Soil_Type14', 'Soil_Type15', 'Soil_Type16', 'Soil_Type17', 'Soil_Type18', 'Soil_Type19', 'Soil_Type20', 'Soil_Type21', 'Soil_Type22', 'Soil_Type23', 'Soil_Type24', 'Soil_Type25', 'Soil_Type26', 'Soil_Type27', 'Soil_Type28', 'Soil_Type29', 'Soil_Type30', 'Soil_Type31', 'Soil_Type32', 'Soil_Type33', 'Soil_Type34', 'Soil_Type35', 'Soil_Type36', 'Soil_Type37', 'Soil_Type38', 'Soil_Type39', 'Soil_Type40', 'label']
trainDf.columns = columns

In [69]:
pd.set_option('display.max_columns', None)
trainDf.head()

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,Wilderness_Area1,Wilderness_Area2,Wilderness_Area3,Wilderness_Area4,Soil_Type1,Soil_Type2,Soil_Type3,Soil_Type4,Soil_Type5,Soil_Type6,Soil_Type7,Soil_Type8,Soil_Type9,Soil_Type10,Soil_Type11,Soil_Type12,Soil_Type13,Soil_Type14,Soil_Type15,Soil_Type16,Soil_Type17,Soil_Type18,Soil_Type19,Soil_Type20,Soil_Type21,Soil_Type22,Soil_Type23,Soil_Type24,Soil_Type25,Soil_Type26,Soil_Type27,Soil_Type28,Soil_Type29,Soil_Type30,Soil_Type31,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,label
0,2410.0,67.0,14.0,60.0,-8.0,1677.0,233.0,212.0,109.0,319.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
1,2739.0,90.0,25.0,210.0,95.0,210.0,248.0,192.0,59.0,743.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
2,3172.0,9.0,7.0,30.0,2.0,1773.0,212.0,225.0,151.0,402.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,2685.0,335.0,23.0,360.0,169.0,990.0,163.0,203.0,176.0,630.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0
4,3131.0,305.0,8.0,258.0,21.0,1909.0,199.0,236.0,176.0,2657.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0

In [70]:
## To check there are no null values
trainDf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 468 entries, 0 to 467
Data columns (total 55 columns):
Elevation                             468 non-null float64
Aspect                                468 non-null float64
Slope                                 468 non-null float64
Horizontal_Distance_To_Hydrology      468 non-null float64
Vertical_Distance_To_Hydrology        468 non-null float64
Horizontal_Distance_To_Roadways       468 non-null float64
Hillshade_9am                         468 non-null float64
Hillshade_Noon                        468 non-null float64
Hillshade_3pm                         468 non-null float64
Horizontal_Distance_To_Fire_Points    468 non-null float64
Wilderness_Area1                      468 non-null float64
Wilderness_Area2                      468 non-null float64
Wilderness_Area3                      468 non-null float64
Wilderness_Area4                      468 non-null float64
Soil_Type1                            468 non-null float64
Soil_Type2                            468 non-null float64
Soil_Type3                            468 non-null float64
Soil_Type4                            468 non-null float64
Soil_Type5                            468 non-null float64
Soil_Type6                            468 non-null float64
Soil_Type7                            468 non-null float64
Soil_Type8                            468 non-null float64
Soil_Type9                            468 non-null float64
Soil_Type10                           468 non-null float64
Soil_Type11                           468 non-null float64
Soil_Type12                           468 non-null float64
Soil_Type13                           468 non-null float64
Soil_Type14                           468 non-null float64
Soil_Type15                           468 non-null float64
Soil_Type16                           468 non-null float64
Soil_Type17                           468 non-null float64
Soil_Type18                           468 non-null float64
Soil_Type19                           468 non-null float64
Soil_Type20                           468 non-null float64
Soil_Type21                           468 non-null float64
Soil_Type22                           468 non-null float64
Soil_Type23                           468 non-null float64
Soil_Type24                           468 non-null float64
Soil_Type25                           468 non-null float64
Soil_Type26                           468 non-null float64
Soil_Type27                           468 non-null float64
Soil_Type28                           468 non-null float64
Soil_Type29                           468 non-null float64
Soil_Type30                           468 non-null float64
Soil_Type31                           468 non-null float64
Soil_Type32                           468 non-null float64
Soil_Type33                           468 non-null float64
Soil_Type34                           468 non-null float64
Soil_Type35                           468 non-null float64
Soil_Type36                           468 non-null float64
Soil_Type37                           468 non-null float64
Soil_Type38                           468 non-null float64
Soil_Type39                           468 non-null float64
Soil_Type40                           468 non-null float64
label                                 468 non-null float64
dtypes: float64(55)
memory usage: 201.2 KB

### Data purity

In [71]:
def checkPurity(data):
    labelColumn = train[:,-1]
    uniqueClasses = np.unique(labelColumn)
    if len(uniqueClasses) == 1:
        return True
    else:
        return False

### Classify

In [72]:
def classifyData(data):
    labelColumn = train[:,-1]
    uniqueClasses, uniqueClassesFrequency = np.unique(labelColumn, return_counts=True)
    index = uniqueClassesFrequency.argmax()
    classification = uniqueClasses[index]
    return classification

### Potenrial Splits

In [73]:
trainDf.head()

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,Wilderness_Area1,Wilderness_Area2,Wilderness_Area3,Wilderness_Area4,Soil_Type1,Soil_Type2,Soil_Type3,Soil_Type4,Soil_Type5,Soil_Type6,Soil_Type7,Soil_Type8,Soil_Type9,Soil_Type10,Soil_Type11,Soil_Type12,Soil_Type13,Soil_Type14,Soil_Type15,Soil_Type16,Soil_Type17,Soil_Type18,Soil_Type19,Soil_Type20,Soil_Type21,Soil_Type22,Soil_Type23,Soil_Type24,Soil_Type25,Soil_Type26,Soil_Type27,Soil_Type28,Soil_Type29,Soil_Type30,Soil_Type31,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,label
0,2410.0,67.0,14.0,60.0,-8.0,1677.0,233.0,212.0,109.0,319.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
1,2739.0,90.0,25.0,210.0,95.0,210.0,248.0,192.0,59.0,743.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
2,3172.0,9.0,7.0,30.0,2.0,1773.0,212.0,225.0,151.0,402.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,2685.0,335.0,23.0,360.0,169.0,990.0,163.0,203.0,176.0,630.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0
4,3131.0,305.0,8.0,258.0,21.0,1909.0,199.0,236.0,176.0,2657.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0

In [74]:
def getPotentialSplits(data):    
    
    poterntialSplits = {}
    totalColumns = np.shape(data)[1]
    
    for columnIndex in range(totalColumns -1):
        poterntialSplits[columnIndex] = []
        values = data[:, columnIndex]
        values.sort()
        uniqueValues = np.unique(values)
                
        # For debugging
        if len(uniqueValues) == 0:
            print("Something is Fishy in the method getPotentialSplits")
            
        # For categorical data
        if len(uniqueValues) == 1:
            if uniqueValues[0] == 0:
                poterntialSplits[columnIndex].append(0.1)
            else:
                poterntialSplits[columnIndex].append(1.1)
            continue                            
                
        for index in range(1,len(uniqueValues)):        
                currentValue  = uniqueValues[index]
                previousValue = uniqueValues[index-1]
                potentialSplit = (currentValue + previousValue) /2                
                poterntialSplits[columnIndex].append(potentialSplit)        
    
    return poterntialSplits

In [87]:
data = train
potentialSplits = getPotentialSplits(data)

In [90]:
trainDf.head(2)

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,Wilderness_Area1,Wilderness_Area2,Wilderness_Area3,Wilderness_Area4,Soil_Type1,Soil_Type2,Soil_Type3,Soil_Type4,Soil_Type5,Soil_Type6,Soil_Type7,Soil_Type8,Soil_Type9,Soil_Type10,Soil_Type11,Soil_Type12,Soil_Type13,Soil_Type14,Soil_Type15,Soil_Type16,Soil_Type17,Soil_Type18,Soil_Type19,Soil_Type20,Soil_Type21,Soil_Type22,Soil_Type23,Soil_Type24,Soil_Type25,Soil_Type26,Soil_Type27,Soil_Type28,Soil_Type29,Soil_Type30,Soil_Type31,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,label
0,2061.0,0.0,1.0,0.0,-75.0,85.0,110.0,129.0,0.0,30.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
1,2075.0,0.0,1.0,0.0,-57.0,95.0,110.0,134.0,31.0,95.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0

### Split Data

In [165]:
def splitData(data, splitColumn, splitValue):    
    splitColumnValues = data[:, splitColumn]
    dataBelow = data[splitColumnValues <= splitValue]
    dataAbove = data[splitColumnValues >  splitValue]    
    return dataBelow, dataAbove

### Lowest Overall Entropy

In [166]:
def calculateEntropy(data):
    
    labelColumn = data[:, -1]
    _, counts = np.unique(labelColumn, return_counts=True)    
    probabilities = counts / counts.sum()
    entropy = sum(probabilities * -np.log2(probabilities))
     
    return entropy

In [167]:
def calculateOverallEntropy(dataBelow, dataAbove):
    
    n = len(dataBelow) + len(dataAbove)
    pDataBelow = len(dataBelow) / n
    pDataAbove = len(dataAbove) / n    
    overallEntropy =  (pDataBelow * calculateEntropy(dataBelow) + pDataAbove * calculateEntropy(dataAbove))
    
    return overallEntropy

In [184]:
dataBelow, dataAbove = splitData(train, 9, 599)
print(len(dataBelow), len(dataAbove))
calculateOverallEntropy(dataBelow, dataAbove)

53 415

1.7616808750367796

In [185]:
def determineBestSplit(data, potentialSplits):
    
    overallEntropy = float("inf")
    for columnIndex in potentialSplits:
        for value in potentialSplits[columnIndex]:
            dataBelow, dataAbove = splitData(data, columnIndex, splitValue=value)
            currentOverallEntropy = calculateOverallEntropy(dataBelow, dataAbove)

            if currentOverallEntropy <= overallEntropy:
                overallEntropy = currentOverallEntropy
                bestSplitColumn = columnIndex
                bestSplitValue = value
    
    return bestSplitColumn, bestSplitValue

In [182]:
potentialSplits = getPotentialSplits(train)
determineBestSplit(train, potentialSplits)

(9, 599.0)

In [191]:
trainContinuous = train[:,:9]
trainNew = np.concatenate((trainContinuous, yTrain.T),axis=1)
print(np.shape(trainNew))
potentialSplits = getPotentialSplits(trainNew)
determineBestSplit(trainNew, potentialSplits)

(468, 10)

(7, 198.5)

In [197]:
dataBelow, dataAbove = splitData(trainNew, 7, 198.5)
print(len(dataBelow), len(dataAbove))
print(calculateOverallEntropy(dataBelow, dataAbove))
print(calculateEntropy(data))

53 415
1.7616808750367796
1.7896384854519598

In [202]:
np.unique(dataBelow[:,-1], return_counts=True )

(array([1., 2., 3., 5., 6.]), array([31, 13,  7,  1,  1]))

In [203]:
np.unique(dataAbove[:,-1], return_counts=True )

(array([1., 2., 3., 4., 5., 6., 7.]),
 array([156, 191,  27,   1,   6,  15,  19]))

In [204]:
np.unique(trainNew[:,-1], return_counts=True )

(array([1., 2., 3., 4., 5., 6., 7.]),
 array([187, 204,  34,   1,   7,  16,  19]))

In [205]:
np.unique(train[:,-1], return_counts=True )

(array([1., 2., 3., 4., 5., 6., 7.]),
 array([187, 204,  34,   1,   7,  16,  19]))

In [207]:

np.unique(yTest, return_counts=True )

(array([1., 2., 3., 4., 5., 6., 7.]),
 array([25027, 79737,  2160,  2160,  2798,  2160,  2160]))